### ISSUE TITLE
请教问题：大佬有没有群组呀，请教一下uniapp中微信分享IOS Universal Links 配置相关

### ISSUE THREAD

**Issue by yayxs** [quanweiwang/uniapp-canvas-drawer#2]
请教问题：大佬有没有群组呀，请教一下uniapp中微信分享IOS Universal Links 配置相关

**Comment by quanweiwang** [comment]
https://www.wangquanwei.com/510.html
看看这篇文章能否解决您的问题

**Comment by yayxs** [comment]
嗯，是看了您这篇文章，现在问题解决了，谢谢，文章写的很好
